# Generated by Django 4.1 on 2022-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventImage',
            field=models.ImageField(null=True, upload_to='post_images', verbose_name='イベントのイメージ'),
        ),
    ]
