# Generated by Django 4.0.6 on 2022-08-25 23:31

import django.core.validators
from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventImage',
            field=models.ImageField(null=True, upload_to=uuid_upload_path.storage.upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png'])], verbose_name='イベントのイメージ'),
        ),
    ]
