# Generated by Django 4.1 on 2022-09-09 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='イベントタイトル')),
                ('location', models.CharField(max_length=100, verbose_name='開催場所')),
                ('description', models.TextField(max_length=2000, verbose_name='イベントの概要')),
                ('dateTime', models.DateTimeField(verbose_name='日時')),
                ('capacity', models.PositiveIntegerField(verbose_name='定員人数')),
                ('EventImage1', models.ImageField(upload_to=events.models.event_images, verbose_name='イベントのイメージ1')),
                ('EventImage2', models.ImageField(upload_to=events.models.event_images, verbose_name='イベントのイメージ2')),
                ('EventImage3', models.ImageField(upload_to=events.models.event_images, verbose_name='イベントのイメージ3')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
