# Generated by Django 4.1 on 2022-09-11 07:48

import auth_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to=auth_api.models.profile_image, verbose_name='プロフィール画像'),
        ),
    ]
