# Generated by Django 4.0.6 on 2022-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to='profile_icon/account_id/%Y/%m/%d/', verbose_name='プロフィールアイコン'),
        ),
    ]
