# Generated by Django 4.0.6 on 2022-08-25 23:41

from django.db import migrations, models
import uuid_upload_path.storage


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to=uuid_upload_path.storage.upload_to, verbose_name='プロフィールアイコン'),
        ),
    ]
