# Generated by Django 4.0.6 on 2022-08-26 00:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_profile_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_icon',
            field=models.ImageField(null=True, upload_to=account.models.profile_icon, verbose_name='プロフィールアイコン'),
        ),
    ]
